SELECT clae2_desc,empleo, clae6_desc
FROM public.distribucion_establecimientos
INNER JOIN public.actividades_establecimientos
ON actividades_establecimientos.clae6 = distribucion_establecimientos.clae6;
